config/routes.rb
Layar::Application.routes.draw do
	root :to => 'layers#index'

  resources :layers do
    resources :interactions, :animations
    resources :hotspots do
      resources :hotspot_objects, :interactions, :animations
    end
  end

	match ':action' => 'static#:action'

end

app/models/layer.rb
class Layer < ActiveRecord::Base
  attr_accessible :biwStyle, :description, :fullRefresh, :iconUrl, :name, :layer_type, :radius, :refreshDistance, :refreshInterval, :showMessage, :title

  has_many :hotspots
  has_many :interactions, :as => :interactionable
  has_many :animations, :as => :animatable

  validates_presence_of :name

  after_create :set_default_type

  def set_default_type
    self.layer_type = 'Geo' if self.layer_type.blank? # Optionally set to 'Visual'
    self.save
    true
  end

end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
	caches_page :show, :if => lambda { |c| c.request.format.json? }
	cache_sweeper :layer_sweeper
#	before_filter :login_required, :except => [:show]
	before_filter(:only => :show) do |controller|
#    login_required unless controller.request.format.json?
  end

  def index
      @layers = Layer.all
      @layer = Layer.new
  end

  def create
    @layer = Layer.new params[:layer]
    if @layer.save
      redirect_to :back, :notice => 'Layer was successfully created.'
    else
      @layers = Layer.all
      render :action => "index"
    end
  end

  def edit
    @layer = Layer.find params[:id]
  end

  def update
    layer = Layer.find params[:id]
    if layer.update_attributes params[:layer]
      redirect_to layers_path, :notice => 'Layer was successfully updated.'
      expire_action :action => :index, :format => :json
    else
      redirect_to :back
    end

  end

  def destroy
    Layer.destroy params[:id]

    redirect_to :back
  end

  def show
    @layer = Layer.find params[:id]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :partial => "layers/show" }
    end
  end
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/views/layers/_show.json.erb
{
  "hotspots": [
    <% @layer.hotspots.each do |hotspot| %>
    {
      "text": {
        "title": "<%= hotspot.title %>",
        "footnote": "<%= hotspot.footnote %>",
        "description": "<%= hotspot.description %>"
      },
      "imageURL": "<%= hotspot.image_url %>",
      "id": "<%= hotspot.id %>",
      "anchor": {
        "geolocation": {
          "lat": <%= hotspot.latitude %>,
          "lon": <%= hotspot.longitude %><% if !hotspot.altitude.blank? %>,
          "alt": <%= hotspot.altitude %><% end %>}
      }<% if !hotspot.interactions.blank? %>,
      "actions": [
      	<% hotspot.interactions.each do |interaction| %>
        {
          "uri": "<%= interaction.uri %>",
          "label": "<%= interaction.label %>",
          "activityType": <%= interaction.activityType %>,     
          "contentType": "<%= interaction.contentType %>",     
          "method": "<%= interaction.method %>"
        }<%= "," unless interaction == hotspot.interactions.last %><% end %>
      ]<% end %>
    }<%= "," unless hotspot == @layer.hotspots.last %>
    <% end %>
  ],
  <% if !@layer.interactions.blank? %>
  "actions": [
  <% @layer.interactions.each do |interaction| %>
    { 
      "uri": "<%= interaction.uri %>",
      "label": "<%= interaction.label %>",
      "activityType": <%= interaction.activityType %>,     
      "contentType": "<%= interaction.contentType %>",     
      "method": "<%= interaction.method %>"
    }<%= "," unless interaction == @layer.interactions.last %>
  <% end %>
  ],
  <% end %>
  "layer": "<%= @layer.name %>",<%= if !@layer.showMessage.blank? then "\n  \"showMessage\": \"#{@layer.showMessage}\",".html_safe end %>
  "biwStyle": "<%= @layer.biwStyle %>",
  "fullRefresh": <%= @layer.fullRefresh %>,<%= if !@layer.radius.blank? then "\n  \"radius\": #{@layer.radius},".html_safe end %><%= if !@layer.refreshInterval.blank? then "\n  \"refreshInterval\": #{@layer.refreshInterval},".html_safe end %><%= if !@layer.refreshDistance.blank? then "\n  \"refreshDistance\": #{@layer.refreshDistance},".html_safe end %><% if !@layer.title.blank? %>
	"showDialog": {
    "title": "<%= @layer.title %>",
    "description": "<%= @layer.description %>",
		"iconUrl": "<%= @layer.iconUrl %>",<% if !@layer.interactions.blank? %>
    "actions": [
    <% @layer.interactions.each do |interaction| %>
      { 
        "uri": "<%= interaction.uri %>",
        "label": "<%= interaction.label %>",
        "activityType": <%= interaction.activityType %>,     
        "contentType": "<%= interaction.contentType %>",     
        "method": "<%= interaction.method %>"
      }<%= "," unless interaction == @layer.interactions.last %>
    <% end %>
    ],
  <% end %>
  },<% end %>	
  "errorCode": 0, 
  "errorString": "ok", 
  "morePages": false, 
  "nextPageKey": null
}

app/views/layers/create.html.erb
<h1>Layers#create</h1>
<p>Find me in app/views/layers/create.html.erb</p>

app/views/layers/delete.html.erb
<h1>Layers#delete</h1>
<p>Find me in app/views/layers/delete.html.erb</p>

app/views/layers/edit.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav nav-pills">
      <li><a href="<%= layers_path %>">Layers</a></li><span class="divider">></span>
      <li class="active"><a href="<%= edit_layer_path(@layer) %>"><span class="label label-warning pull-left">EDIT</span><%= @layer.name %></a>
    </ul>
  </div>
</div>

<div class="row">
  <%= form_for @layer, :html => { :class => "form-horizontal"} do |f| %>
    <div class="span4">
      <div class="well well-small">
        Editing 
      </div>
    </div>
    <div class="span8">

      <div class="row">
        <div class="span4">

          <div class="control-group">
            <%= f.label :name, :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :name, :class => "input-medium" %>
            </div>
          </div>

          <div class="control-group">
            <label class="control-label">Layer Type</label>
            <div class="controls">
              <label class="radio inline"><%= f.radio_button :layer_type, "Geo" %>Geo</label>
              <label class="radio inline"><%= f.radio_button :layer_type, "Visual" %>Visual</label>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :radius, :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :radius, :class => "input-medium" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :refreshInterval, "Refresh Interval", :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :refreshInterval, :class => "input-medium" %>
            </div>
          </div>
          
          <div class="control-group">
            <%= f.label :refreshDistance, "Refresh Distance", :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :refreshDistance, :class => "input-medium" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :fullRefresh, "Full Refresh", :class => 'control-label' %>
            <div class="controls">
              <%= f.check_box :fullRefresh %>
            </div>
          </div>


          <%= f.submit 'Update Layer', :class => 'btn btn-primary' %>
          <a href="<%= layers_path() %>" class="btn btn-danger">Cancel</a>

        </div>
        <div class="span4">
          
          <div class="control-group">
            <% biwStyles = { "Classic" => "classic", "Collapsed" => "collapsed" } %>
            <%= f.label :biwStyle, "BIW Style", :class => 'control-label' %>
            <div class="controls">
              <%= f.select :biwStyle, biwStyles, {}, {:class => "input-medium"} %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :showMessage, "Show Message", :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :showMessage, :class => "input-medium" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :title, :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :title, :class => "input-medium" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :iconUrl, "Icon URL", :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :iconUrl, :class => "input-medium" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :description, :class => 'control-label' %>
            <div class="controls">
              <%= f.text_area :description, :rows => "4", :class => "input-medium" %>
            </div>
          </div>


        </div>
      </div>

    </div>


  <% end %>

</div>

app/views/layers/index.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav nav-pills">
      <li class="active"><a href="<%= layers_path %>">All Layers</a></li>
    </ul>
		<div class="btn-group pull-right">
    	<button href="" class="btn btn-info" data-toggle="button">
      	<i class="icon-info-sign icon-white"></i>  Tips
    	</button>
    	<a href="/help" class="btn btn-info">Help Docs</a>
		</div>
  </div>
</div>

<% if notice %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>

<div class='row'>
  <div class='span4'>

  <%= form_for @layer, :html => { :class => ""} do |f| %>
    
    <% if @layer.errors.any? %>
      <div class="alert alert-error">
      <h4>Error!</h4>
        <ul class=''>
          <% @layer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% else %>
      <% end %>
    

    <div class='input-append well well-small'>
      <%= f.text_field :name, :placeholder => "Add a New Layer", :class => 'input-medium' %>
      <%= f.submit 'Create Layer', :class => "btn btn-success" %>
    </div>
  <% end %>
    <div class="alert alert-info">
      <h2>Get Started:</h2>
			<p>Three pieces are needed to successfully publish a virtual tour:</p>
			<ol>
				<li>
					<h4>Hotspot Database</h4>
					<p>Using this web application, create a layer and add hotspots to its 'show' page.
					The information created there will be added to the layer's json page.</p>
				</li>
				<li>
					<h4>Layar.com Publication</h4>
					<p>Create a layer at <a href="http://layar.com" target="_blank">Layar.com</a> and after completing the requirements, request publication.</p>
				</li>
				<li>
					<h4>Static Web Server</h4>
					<p>This database only holds the minimum amount of information. Additional interactivity (photos, images, audio) must be stored on another webserver.</p>
				</li>
			</ol>
			<p>Read the <a href="/help">Help Docs</a> for tutorials and more information.</p>
    </div>
  </div>

  <div class='span8'>
    <table class='table table-bordered'>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Hotspots</th>
      <th>Actions</th>
      <th>Animations</th>
      <th>
    </tr>

    <% for layer in @layers %>
    <tr id="layer_<%= layer.id %>">
      <td><h3><%= layer.name %></h3></td>
      <td><h3><%= layer.layer_type %></h3></td>
      <td class="hotspots"><h1><%= layer.hotspots.count %></h1></td>
			<td class="actions"><h1><%= layer.interactions.count %></h1></td>
			<td class="animations"><h1><%= layer.animations.count %></h1></td>
      <td class="btns">
        <%= link_to 'Add Info', layer_path(layer), html_options = { :class => "btn btn-success btn-mini" } %>
        <%= link_to 'Edit Meta', edit_layer_path(layer), html_options = { :class => "btn btn-warning btn-mini" } %>
				<%= link_to 'Delete', layer, :data => { :confirm => "Are you sure you want to delete '#{layer.name}'?" }, :method => :delete, :class => "btn btn-danger btn-mini" %>
      </td>
    </tr>
    <% end -%>
    </table>
  </div>
</div>

app/views/layers/show.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav nav-pills">
      <li><a href="<%= layers_path %>">Layers</a></li><span class="divider">></span>
      <li class="active"><a href="<%= layer_path(@layer) %>"><%= @layer.name %></a></li>
    </ul>
		<div class="btn-group pull-right">
    	<button href="" class="btn btn-info" data-toggle="button">
      	<i class="icon-info-sign icon-white"></i>  Tips
    	</button>
    	<a href="" class="btn btn-info">Help Docs</a>
		</div>
    <a href="<%= layer_path(@layer) + '.json' %>" style="margin-right:10px;" target="_blank" class="btn pull-right">
      <i class="icon-align-justify"></i> .json
    </a>
  </div>
</div>

<% if notice %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>

<h2><%= @layer.hotspots.count %> Hotspots
  <%= link_to( new_layer_hotspot_path(@layer), :class => "btn btn-success" ) do %>
    <i class="icon-plus icon-white"></i> Add Hotspot
  <% end %>
</h2>


<table class="table table-bordered table-striped">
  <tr>
    <th style="width:110px;"></th>
    <th>Title - Footnote</th>
    <th style="max-width:155px;">Coordinates</th>
    <th style="width:200px;">Description</th>
    <th></th>
  </tr>

<% @layer.hotspots.each do |hotspot| %>
  <tr id="hotspot_<%= hotspot.id %>">
    <td>
			<% 	
				if(!hotspot.image_url.blank?) 
					imgSRC = hotspot.image_url
				else
					imgSRC = "http://placehold.it/100x75"
				end
			%>
      <img src="<%= imgSRC %>" width="100px" height="75px" class="img-polaroid"/>
    </td>
    <td class="title">
				<h2><%= hotspot.title %></h2>
    		<h5><%= hotspot.footnote %></h5>
		</td>
    <td class="lyshow latlon">
				<dl class="dl-horizontal">
					<dt>Lat:</dt><dd><%= hotspot.latitude %></dd></h4>
					<dt>Lon:</dt><dd><%= hotspot.longitude %></dd></h4>
					<% if !hotspot.altitude.blank? %>
						<dt>Alt:</dt><dd><%= hotspot.altitude %></dd></h4>
					<% end %>
				</dl>
		</td>
    <td><%= hotspot.description %></td>
    <td id="hotspotActions" class="btns">
      <%= link_to 'Show', layer_hotspot_path(@layer, hotspot), html_options = { :class => "btn btn-primary btn-mini" } %>
      <%= link_to 'Edit', edit_layer_hotspot_path(@layer, hotspot), html_options = { :class => "btn btn-warning btn-mini" } %>
			<%= link_to 'Delete', layer_hotspot_path(@layer, hotspot), :data => { :confirm => "Are you sure you want to delete '#{hotspot.title}'?" }, :method => :delete, :class => "btn btn-danger btn-mini" %>
    </td>
  </tr>
<% end %>
</table>

<h2><%= @layer.interactions.count %> Actions
  <%= link_to( new_layer_interaction_path(@layer), :class => "btn btn-success" ) do %>
    <i class="icon-plus icon-white"></i> Add Action
  <% end %>
</h2>

<table class="table table-bordered table-striped">
  <tr>
    <th>Label</th>
    <th style="width:200px;">URI</th>
    <th>Content Type</th>
    <th>Method</th>
    <th style="width:100px;"></th>
  </tr>

<% @layer.interactions.each do |interaction| %>
  <tr id="interaction_<%= interaction.id %>">
    <td><%= interaction.label %></td>
    <td><%= interaction.uri %></td>
    <td><%= interaction.contentType %></td>
    <td><%= interaction.method %></td>
    <td id="interactionActions" class="btn-group">
      <%= link_to 'Show', layer_interaction_path(@layer, interaction), html_options = { :class => "btn btn-primary btn-mini" } %>
      <%= link_to 'Edit', edit_layer_interaction_path(@layer, interaction), html_options = { :class => "btn btn-warning btn-mini" } %>
      <%= link_to 'Delete', layer_interaction_path(@layer, interaction), :method => 'delete', :class => "btn btn-danger btn-mini" %>
    </td>
  </tr>
<% end %>
</table>

<h2>Animations</h2>