config/routes.rb
Layar::Application.routes.draw do
	root :to => 'layers#index'

  resources :layers do
    resources :interactions, :animations
    resources :hotspots do
      resources :hotspot_objects, :interactions, :animations
    end
  end

	match ':action' => 'static#:action'

end

app/models/hotspot.rb
class Hotspot < ActiveRecord::Base
  attr_accessible :altitude, :biwStyle, :ciwIcon_type, :ciwIcon_url, :description, :footnote, :image_url, :inFocus, :latitude, :longitude, :showBiwOnClick, :showSmallBiw, :title, :interactions_attributes, :hotspot_object_attributes

  belongs_to :layer

  has_many :interactions, :as => :interactionable
  accepts_nested_attributes_for :interactions, :allow_destroy => :true, :reject_if => proc { |attributes| attributes['label'].blank? }

	has_one :hotspot_object
  accepts_nested_attributes_for :hotspot_object, :allow_destroy => :true

  validates_presence_of :title, :latitude, :longitude
  validates_uniqueness_of :title


end

app/controllers/hotspots_controller.rb
class HotspotsController < ApplicationController
#	before_filter :login_required
	cache_sweeper :hotspot_sweeper

  def index
  end

  def new
    @layer = Layer.find params[:layer_id]
    @hotspot = @layer.hotspots.new
		# Default values for Eau Claire WI
			@hotspot.latitude = 44.79835779383246 
			@hotspot.longitude = -91.49950504232788
    @interaction = @hotspot.interactions.new
			@interaction.contentType = "text/html"
			@interaction.activityType = 1
		@hotspot_object = @hotspot.build_hotspot_object
			@hotspot_object.contentType = "image/vnd.layar.generic"
  end

  def create
    @layer = Layer.find params[:layer_id]
    @hotspot = @layer.hotspots.create params[:hotspot]
    if @hotspot.save
      render "show", :notice => 'Hotspot was successfully created.' 
    else
      render :action => "new"
    end

  end

  def edit
    @layer = Layer.find params[:layer_id]
    @hotspot = @layer.hotspots.find params[:id]
    @interaction = @hotspot.interactions.new
			@interaction.contentType = "text/html"
			@interaction.activityType = 1
		if !@hotspot.hotspot_object then 
			@hotspot.build_hotspot_object
			@hotspot.hotspot_object.contentType = "image/vnd.layar.generic"
		end
  end

  def update
    layer = Layer.find params[:layer_id]
    hotspot = layer.hotspots.find params[:id]
    if hotspot.update_attributes params[:hotspot]
      redirect_to layer_hotspot_path(layer, hotspot), :notice => 'Hotspot successfully updated.'
    else
      redirect_to :back, :notice => 'Hotspot not updated.'
    end
  end

  def destroy
    @layer = Layer.find params[:layer_id]
    @layer.hotspots.destroy params[:id]

    redirect_to layer_path(@layer), :notice => 'Hotspot successfully deleted'
  end

  def show
    @layer = Layer.find params[:layer_id]
    @hotspot = @layer.hotspots.find params[:id]
		@object = @hotspot.hotspot_object
  end
end

app/helpers/hotspot_helper.rb
module HotspotHelper
end

app/views/hotspots/_form.html.erb
<%= form_for [@layer, @hotspot], :html => { :class => "form-horizontal"} do |f| %>
  <% if @hotspot.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <ul>
      <% @hotspot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
	<div class="span12">
		<h2>
			<%= params[:action].capitalize %> Hotspot
  		<%= link_to "Cancel", layer_path(@layer), :class => "btn btn-danger pull-right" %>
  		<%= f.submit :class => "btn pull-right" %>
		</h2>
	</div>
</div>

<div class="row">
	<div class="span6">
  	<div class="control-group">
    	<%= f.label :title, :class => 'control-label' %>
    	<div class="controls">
      	<%= f.text_field :title, :class => 'input-xlarge' %>
    	</div>
  	</div>

  	<div class="control-group"> 
    	<%= f.label :footnote, :class => 'control-label' %>
    	<div class="controls">
      	<%= f.text_field :footnote, :class => 'input-xlarge' %>
    	</div>
  	</div>
  
  	<div class="control-group"> 
    	<%= f.label :description, :class => 'control-label' %>
    	<div class="controls">
      	<%= f.text_area :description, :class => 'input-xlarge', :rows => "4" %>
			</div>
 	 	</div>
  
  	<div class="control-group"> 
   	 <%= f.label :image_url, :class => 'control-label' %>
   	 <div class="controls">
  	    <%= f.text_area :image_url, :class => 'input-xlarge', :rows => "4" %>
 	   </div>
	  </div>
	</div>

	<div class="span6">
		<fieldset class="gllpLatlonPicker thumbnail">
			<div class="gllpMap">Google Maps</div>
			<input type="hidden" class="gllpZoom" value="16"/>

			<div class='form-inline'>
    		<%= f.label :latitude, "Lat:" %>
      	<%= f.text_field :latitude, :class => 'input-small gllpLatitude' %>
    		<%= f.label :longitude, "Lon:" %>
      	<%= f.text_field :longitude, :class => 'input-small gllpLongitude' %>
    		<%= f.label :altitude, "Alt:" %>
      	<%= f.text_field :altitude, :class => 'input-mini gllpAltitude' %> 
			</div>
		</fieldset>
	</div> <!-- End span7 -->
</div> <!-- End Hotspot row with map -->

<ul class="nav nav-tabs" id="hotspottabs">
	<li><a href="#object" data-toggle="tab"><h4>Object</h4></a></li>
	<li><a href="#actions" data-toggle="tab"><h4>Actions</h4></a></li>
	<li><a href="#animations" data-toggle="tab"><h4>Animations</h4></a></li>
	<li><a href="#options" data-toggle="tab"><h4><i class="icon-cog"></i> Optional Settings</h4></a></li>
</ul>

<div class="row">  
	<div class="span12 tab-content">
  	<div class="form-inline tab-pane" id="options"> 
			<h3>Optional Settings</h3>
			<div class="row">
				<div class="span3 offset1">
    			<div class="control-group">
        		<%= f.label :showSmallBiw, "Show Small BIW", :class => 'control-label' %>
						<div class="controls"><%= f.check_box :showSmallBiw, :class => 'input-medium' %></div>
    			</div>
    			<div class="control-group">
        		<%= f.label :showBiwOnClick, "Show BIW on Click", :class => 'control-label' %>
						<div class="controls"><%= f.check_box :showBiwOnClick, :class => 'input-medium' %></div>
    			</div>
    			<div class="control-group">
        		<%= f.label :inFocus, "In Focus", :class => 'control-label' %>
						<div class="controls"><%= f.check_box :inFocus, :class => 'input-medium' %></div>
    			</div>
				</div>
				<div class="span4">
    			<div class="control-group">
        		<%= f.label :biwStyle, "BIW Style", :class => 'control-label' %>
						<div class="controls"><%= f.text_field :biwStyle, :class => 'input-medium' %></div>
    			</div>
    			<div class="control-group">
        		<%= f.label :ciwIcon_type, "CIW Icon Type", :class => 'control-label' %>
						<div class="controls"><%= f.text_field :ciwIcon_type, :class => 'input-medium' %></div>
    			</div>
    			<div class="control-group">
        		<%= f.label :ciwIcon_url, "CIW Icon URL", :class => 'control-label' %>
						<div class="controls"><%= f.text_field :ciwIcon_url, :class => 'input-medium' %></div>
    			</div>
				</div>
			</div>
		</div> <!-- End tab-pane #options -->

		<div class="form-inline tab-pane" id="object">
			<%= f.fields_for :hotspot_object do |builder| %>
				<% if :hotspot_object.blank? then %>
					<h3 class="">New Object</h3>
				<% else %>
					<h3>Hotspot Object
						<div class="form-inline">
 							<%= builder.check_box :_destroy %>
   	 					<%= builder.label :_destroy, "Delete Object" %>
 						</div>
					</h3>		
				<% end # hotspot_object if  %>
			
				<div class="row">
					<div class="span4">	
      			<% contentTypes = { 
        			"Generic Image" => "image/vnd.layar.generic",
							"jpeg" => "image/jpeg",
							"gif" => "image/gif",
							"png" => "image/png",
        			"3D model" => "model/vnd.layar.l3d", 
        			"AR Video" => "video/mp4"
      			} %>
    				<div class="control-group">
        			<%= builder.label :contentType, "Content Type", :class => 'control-label' %>
							<div class="controls"><%= builder.select :contentType, contentTypes, {}, {:class => 'input-medium'} %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :hotspot_object_url, "URL", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :hotspot_object_url, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :reducedUrl, "Reduced URL", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :reducedUrl, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :size, "Size", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :size, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :previewImage, "Preview Image", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :previewImage, :class => 'input-medium' %></div>
    				</div>
					</div>
					<div class="span4">	
    				<div class="control-group">
        			<%= builder.label :translateX, "Translate X", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :translateX, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :translateY, "Translate Y", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :translateY, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :translateZ, "Translate Z", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :translateZ, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :scale, :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :scale, :class => 'input-medium' %></div>
    				</div>
					</div>
					<div class="span4">	
    				<div class="control-group">
        			<%= builder.label :rotateAxisX, "Rotate Axis X", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :rotateAxisX, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :rotateAxisY, "Rotate Axis Y", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :rotateAxisY, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :rotateAxisZ, "Rotate Axis Z", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :rotateAxisZ, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :rotateAngle, "Rotate Angle", :class => 'control-label' %>
							<div class="controls"><%= builder.text_field :rotateAngle, :class => 'input-medium' %></div>
    				</div>
    				<div class="control-group">
        			<%= builder.label :rotateRel, "Rotation Relative", :class => 'control-label' %>
							<div class="controls"><%= builder.check_box :rotateRel, :class => 'input-medium' %></div>
    				</div>
					</div>
				</div>
			<% end %>
		</div>

<div class="tab-pane" id="actions"> 
	<% @hotspot.interactions.each.with_index do |interaction, index|%>
		<%= f.fields_for :interactions, interaction do |builder| %>
			<% if interaction == @interaction %>
				<h3 class="">New Action</h3>
			<% else %>
				<h3>Action <%= index + 1 %>
					<div class="form-inline">
 	  				<%= builder.check_box :_destroy %>
   		 			<%= builder.label :_destroy, "Delete Action" %>
  				</div>
				</h3>		
			<% end # interaction if  %>

		<div class="row">
			<div class="span4">	
    		<div class="control-group">
        	<%= builder.label :label, :class => 'control-label' %>
					<div class="controls"><%= builder.text_field :label, :class => 'input-medium' %></div>
    		</div>
    
    		<div class="control-group">
      		<%= builder.label :uri, 'URI', :class => 'control-label' %>
      		<div class="controls">
        	<!-- <select class='input-small'>
          <option value="http://">http://</option>
          <option value="https://">https://</option>
          <option value="tel:">tel:</option>
          <option value="mailto:">mailto:</option>
          <option value="sms:">sms:</option>
          <option value="layar://">layar://</option>
          <option value="layarshare://">layarshare://</option>
          <option value=""></option>
        	</select> -->
        		<%= builder.text_field :uri, :class => 'input-medium' %>
      		</div>
    		</div>
    
    		<div class="control-group">
      		<% contentTypes = { 
        		"HTML" => "text/html", "Text" => "text/plain",
        		"Audio MPEG" => "audio/mpeg", "Audio MP4" => "audio/mp4", 
        		"Video MP4" => "video/mp4", "Video 3GPP" => "video/3gpp",
        		"Internal Custom Call" => "application/vnd.layar.internal"
      		} %>
      		<%= builder.label :contentType, 'Content Type', :class => 'control-label' %>
      		<div class="controls"><%= builder.select :contentType, contentTypes, {}, {:class => "input-medium"} %></div>
    		</div>

    		<div class="control-group"> 
    			<% activityTypes = { 
      			"Info"        =>  "1", "Audio"              =>  "2", "Video"          =>  "3", "Call"             =>  "4",
						"Email"       =>  "5", "Position/Map"       =>  "6", "Add"            =>  "7", "Remove"           =>  "8",
    			  "Edit"        =>  "9", "Collect"            => "10", "Play"           => "11", "Make Move"        => "12",
   			  	"Share"       => "13", "Pin on Map"         => "14", "Check In/Out"   => "15", "Log In/Out"       => "16",
     				"Lock/Unlock" => "17", "List/Scores"        => "18", "Money/Pay/Buy"  => "19", "Open"             => "20",
    				"Close"       => "21", "Search"             => "22", "Update"         => "23", "Layer"            => "24",
      			"Yes"         => "25", "Increase/Decrease"  => "26", "View/Examine"   => "27", "Add to Favorites" => "28",
      			"Kill/Hit"    => "29", "Heal"               => "30", "Defend"         => "31", "Repair"           => "32",
      			"Use/Switch"  => "33", "Animate"            => "34", "Scoreboard"     => "35", "Generic Action"   => "36",
      			"No"          => "37"
   			 	} %>
      		<%= builder.label :activityType, 'Activity Type', :class => 'control-label' %>
      		<div class="controls"><%= builder.select :activityType, activityTypes, {}, {:class => "input-medium"} %></div>
    		</div>
			</div> <!-- End first column -->
	
			<div class="span2">
    		<div class="control-group"> 
      		<%= builder.label :showActivity, 'Show Activity', :class => 'control-label' %>
      		<div class="controls"><%= builder.check_box :showActivity %></div>
    		</div>
    
    		<div class="control-group"> 
      		<%= builder.label :closeBiw, 'Close BIW', :class => 'control-label' %>
      		<div class="controls"><%= builder.check_box :closeBiw %></div>
    		</div>
    
    		<div class="control-group"> 
      		<%= builder.label :autoTrigger, 'Auto Trigger', :class => 'control-label' %>
      		<div class="controls"><%= builder.check_box :autoTrigger %></div>
    		</div>
    
    		<div class="control-group"> 
      		<%= builder.label :autoTriggerOnly, 'Auto Trigger Only', :class => 'control-label' %>
      		<div class="controls"><%= builder.check_box :autoTriggerOnly %></div>
    		</div>
			</div> <!-- End second column -->

    	<div class="span4">
				<div class="control-group">
    			<% methods = { "GET" => "GET", "POST" => "POST" } %>
      		<%= builder.label :method, :class => 'control-label' %>
      		<div class="controls"><%= builder.select :method, methods, {}, {:class => "input-medium"} %></div>
    		</div>

    		<div class="control-group"> 
      		<%= builder.label :params, :class => 'control-label' %>
      		<div class="controls"><%= builder.text_field :params, :class => 'input-medium' %></div>
    		</div>
        
    		<div class="control-group"> 
      		<%= builder.label :activityMessage, 'Activity Message', :class => 'control-label' %>
      		<div class="controls"><%= builder.text_field :activityMessage, :class => 'input-medium' %></div>
    		</div>
				
    		<div class="control-group"> 
      		<%= builder.label :autoTriggerRange, 'Auto Trigger Range', :class => 'control-label' %>
      		<div class="controls"><%= builder.text_field :autoTriggerRange, :class => 'input-medium'%></div>
    		</div>
			</div> <!-- End third column -->
		</div> <!-- End Actions Row -->
	<% end %>
  <% end %>
  
	</div>
</div>
  <%= f.submit :class => "btn" %>
  <%= link_to "Cancel", layer_path(@layer), :class => "btn btn-danger" %>

<% end %>

app/views/hotspots/create.html.erb
<h1>Hotspot#create</h1>
<p>Find me in app/views/hotspot/create.html.erb</p>

app/views/hotspots/delete.html.erb
<h1>Hotspot#delete</h1>
<p>Find me in app/views/hotspot/delete.html.erb</p>

app/views/hotspots/edit.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav nav-pills">
      <li><a href="<%= layers_path %>">Layers</a></li><span class="divider">></span>
      <li><a href="<%= layer_path(@layer) %>"><%= @layer.name %></a></li><span class="divider">></span>
      <li class="active"><a href="<%= layer_hotspot_path(@layer, @hotspot) %>"><span class="label label-warning pull-left">EDIT</span>'<%= @hotspot.title %>' Hotspot</a></li>
    </ul>
		<div class="btn-group pull-right">
    	<button href="" class="btn btn-info" data-toggle="button">
      	<i class="icon-info-sign icon-white"></i>  Tips
    	</button>
    	<a href="" class="btn btn-info">Help Docs</a>
		</div>
  </div>
</div>

<%= render :partial => "form" %>

app/views/hotspots/index.html.erb
<h1>Hotspot#index</h1>
<p>Find me in app/views/hotspot/index.html.erb</p>

app/views/hotspots/new.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav nav-pills">
      <li><a href="<%= layers_path %>">Layers</a></li><span class="divider">></span>
      <li><a href="<%= layer_path(@layer) %>"><%= @layer.name %></a></li><span class="divider">></span>
      <li class="active"><a><span class="label label-success pull-left">NEW</span>Hotspot</a></li>
      
    </ul>
  </div>
</div>
<%= render :partial => "form" %>

app/views/hotspots/show.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav nav-pills">
      <li><a href="<%= layers_path %>">Layers</a></li><span class="divider">></span>
      <li><a href="<%= layer_path(@layer) %>"><%= @layer.name %></a></li><span class="divider">></span>
      <li class="active"><a href="<%= layer_hotspot_path(@layer, @hotspot) %>"><span class="label label-info pull-left">SHOW</span> '<%= @hotspot.title %>' Hotspot</a></li>
    </ul>
		<div class="btn-group pull-right">
    	<button href="" class="btn btn-info" data-toggle="button">
      	<i class="icon-info-sign icon-white"></i>  Tips
    	</button>
    	<a href="" class="btn btn-info">Help Docs</a>
		</div>
  </div>
</div>

<% if notice %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>

<h2>Hotspot
	<div class="pull-right">
  <%= link_to( new_layer_hotspot_path(@layer), :class => "btn btn-success" ) do %>
    <i class="icon-plus icon-white"></i> Add
  <% end %>
  <%= link_to( edit_layer_hotspot_path(@layer, @hotspot), :class => "btn btn-warning" ) do %>
    Edit
  <% end %>
	<%= button_to 'Delete', layer_hotspot_path(@layer, @hotspot), :method => 'delete', :class => "btn btn-danger" %>
	</div>
</h2>
<table class="table table-bordered table-striped">
  <tr>
    <th style="width:110px;"></th>
    <th>Title - Footnote</th>
    <th style="width:254px;">Coordinates</th>
    <th style="width:184px;">Description</th>
  </tr>

  <tr id="hotspot_<%= @hotspot.id %>">
    <td>
				<% 	
					if(!@hotspot.image_url.blank?) 
						imgSRC = @hotspot.image_url
					else
						imgSRC = "http://placehold.it/100x75"
					end
				%>
      	<img src="<%= imgSRC %>" width="100px" height="75px" class="img-polaroid"/>
		</td>
    <td class="title">
				<h2><%= @hotspot.title %></h2>
    		<h5><%= @hotspot.footnote %></h5>
		</td>
    <td class="hsshow latlon">
				<dl class="dl-horizontal">
					<dt>Latitude:</dt><dd><%= @hotspot.latitude %></dd></h4>
					<dt>Longitude:</dt><dd><%= @hotspot.longitude %></dd></h4>
					<% if !@hotspot.altitude.blank? %>
						<dt>Altitude:</dt><dd><%= @hotspot.altitude %></dd></h4>
					<% end %>
				</dl>
		</td>
		<td>
			<%= @hotspot.description %>
		</td>
</table>
<div class="row">
	<div class="span12">
		<fieldset class="thumbnail pull-right gllpLatlonPicker">
			<div class="gllpMap">Google Maps</div>
			<input type="hidden" class="gllpLatitude" value="<%= @hotspot.latitude %>"/>
			<input type="hidden" class="gllpLongitude" value="<%= @hotspot.longitude %>"/>
			<input type="hidden" class="gllpZoom" value="16"/>
		</fieldset>

		<h4>Optional Settings</h4>
		<dl class="dl-horizontal pull-left hsinfo">
        <dt>Show Small BIW:</dt>    <dd><%= @hotspot.showSmallBiw %></dd>
        <dt>Show BIW on Click:</dt>    <dd><%= @hotspot.showBiwOnClick %></dd>
        <dt>BIW Style:</dt>          <dd><%= @hotspot.biwStyle %></dd>
        <dt>CIW Icon URL:</dt>       <dd><%= @hotspot.ciwIcon_url %></dd>
        <dt>CIW Icon Type:</dt>      <dd><%= @hotspot.ciwIcon_type %></dd>
        <dt>inFocus:</dt>           <dd><%= @hotspot.inFocus %></dd>
    </dl>
	</div>
</div>

<ul class="nav nav-tabs" id="hotspottabs">
	<li><a href="#object" data-toggle="tab"><h4><%= if !@hotspot.hotspot_object.blank? then "1 Object" else "0 Objects" end %></h4></a></li>
	<li><a href="#actions" data-toggle="tab"><h4><%= @hotspot.interactions.count %> Action<%= if @hotspot.interactions.count != 1 then "s" end %></h4></a></li>
	<li><a href="#animations" data-toggle="tab"><h4>Animations</h4></a></li>
</ul>

<div class="row">
	<div class="span12 tab-content">
		<div class="tab-pane" id="object">
		<% if @object then %>
			<h3>Object</h3>
				<dl class="dl-horizontal span11">
					<dt>Full URL:</dt>		       	<dd><%= @object.hotspot_object_url %></dd>
					<dt>Reduced URL:</dt>       	<dd><%= @object.reducedUrl %></dd>
				</dl>
      <div class="row">
				<dl class="dl-horizontal span4">
					<dt>Content Type:</dt>       	<dd><%= @object.contentType %></dd>
					<dt>Size:</dt> 				      	<dd><%= @object.size %></dd>
					<dt>Preview Image:</dt>       <dd><%= @object.previewImage %></dd>
				</dl>
				<dl class="dl-horizontal span3">
					<dt>Translate X:</dt>       	<dd><%= @object.translateX %></dd>
					<dt>Translate Y:</dt> 				<dd><%= @object.translateY %></dd>
					<dt>Translate Z:</dt>       	<dd><%= @object.translateZ %></dd>
					<dt>Scale:</dt>				 	     	<dd><%= @object.scale %></dd>
				</dl>
				<dl class="dl-horizontal span4">
					<dt>Rotate Axis X:</dt>       <dd><%= @object.rotateAxisX %></dd>
					<dt>Rotate Axis Y:</dt> 			<dd><%= @object.rotateAxisY %></dd>
					<dt>Rotate Axis Z:</dt>       <dd><%= @object.rotateAxisZ %></dd>
					<dt>Rotate Angle:</dt>       	<dd><%= @object.rotateAngle %></dd>
					<dt>Rotation Rel:</dt>   <dd><%= @object.rotateRel %></dd>
				</dl>
			</div>
		<% end %>
		</div>
		<div class="tab-pane" id="actions">
			<% @hotspot.interactions.each.with_index do |interaction, index| %>
			<h3>Action <%= index + 1 %></h3>
			<div class="row">
				<div class="span10 offset1">
					<dl class="dl-horizontal pull-left hsinfo">
        		<dt>Action Label:</dt>       	<dd><%= interaction.label%></dd>
						<dt>URI:</dt> 		          	<dd>
																							<a href="<%= interaction.uri %>" target="_blank">
																								<%= interaction.uri %>
																							</a>		
																					</dd>
					</dl>
					<dl class="dl-horizontal pull-left hsinfo">
       			<dt>Content Type:</dt>      	<dd><%= interaction.contentType %></dd>
        		<dt>Activity Type:</dt>    		<dd><%= interaction.activityType %></dd>
        		<dt>Show Activity:</dt>    	 	<dd><%= interaction.showActivity %></dd>
        		<dt>Activity Message:</dt> 		<dd><%= interaction.activityMessage %></dd>
        		<dt>Method:</dt>            	<dd><%= interaction.method %></dd>
					</dl>
					<dl class="dl-horizontal pull-left hsinfo">
        		<dt>Params:</dt>            	<dd><%= interaction.params %></dd>
        		<dt>Close BIW:</dt>       	  <dd><%= interaction.closeBiw %></dd>
        		<dt>Auto Trigger Range:</dt>  <dd><%= interaction.autoTriggerRange %></dd>
        		<dt>Auto Trigger:</dt>        <dd><%= interaction.autoTrigger %></dd>
        		<dt>Auto Trigger Only:</dt>   <dd><%= interaction.autoTriggerOnly %></dd>
    			</dl>
				</div>
			</div> <!-- End each action row -->
			<% end %>
		</div>
	</div>
</div>

<h2>
<%= link_to "Back to Layer", layer_path(@layer), :class => 'btn' %>
  <%= link_to( edit_layer_hotspot_path(@layer, @hotspot), :class => "btn btn-warning" ) do %>
    Edit Hotspot
  <% end %>
	<%= button_to 'Delete Hotspot', layer_hotspot_path(@layer, @hotspot), :method => 'delete', :class => "btn btn-danger" %>
</h2>

app/views/hotspots/update.html.erb
<h1>Hotspot#update</h1>
<p>Find me in app/views/hotspot/update.html.erb</p>